apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.ratings.namespace }}
spec:
  type: {{ .Values.ingress.serviceType }}
  ports:
  - port: {{ .Values.ratings.port }}
  selector:
    app: {{ .Release.Name }}

# apiVersion: v1
# kind: Service
# metadata:
#   name: bookinfo-dev-ratings
#   namespace: student28-bookinfo-dev
# spec:
#   type: ClusterIP
#   ports:
#   - port: 8080
#   selector:
#     app: bookinfo-dev-ratings
