apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.ratings.namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /student20/ratings(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: {{ .Values.ratings.port }}

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#   name: bookinfo-dev-ratings
#   namespace: student28-bookinfo-dev
# spec:
#   rules:
#   - host: itkmitl.bookinfo.dev.opsta.net
#     http:
#       paths:
#       - path: /student28/ratings(/|$)(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: bookinfo-dev-ratings
#             port:
#               number: 8080